### ISSUE TITLE
Kuristina is completely broken now

### ISSUE THREAD

**Issue by racinmat** [TimboKZ/kuristina#1]
Hi, kuristina stopped working, seems to fail in parsing MAL, both anime and manga. It fails even for example address, https://kuristina.herokuapp.com/anime/Timbo_KZ.json. 
It seems something has changed in DOM structure, I had to fix other crawler I was using.

**Comment by TimboKZ** [comment]
This notice now appears when you log in on the MAL website:

![Notice about the MAL API vulnerability](https://user-images.githubusercontent.com/5504588/40503905-6cc413e2-5f44-11e8-9541-411ddef2f9cf.png)

They mentioned their API is only temporarily unavailable (namely `malappinfo.php`), so I'll wait a couple of days before resolving this.

**Comment by TimboKZ** [comment]
MAL are sure taking their time...

**Comment by vaibhav29498** [comment]
It seems that MAL is working completely fine now, but Kuristina is still broken.

**Comment by TimboKZ** [comment]
It seems https://myanimelist.net/malappinfo.php is still dead, and I'm not sure if it's even coming back. Might be worth looking into alternatives for Kuristina, I heard some of them work already.

**Comment by vaibhav29498** [comment]
I looked into some other MAL APIs, but none of them seems to be supporting anime lists. I need that functionality for a project of mine. If you get to know about any such API then please do tell. Thanks.

**Comment by TimboKZ** [comment]
Hey people - Jikan has been updated to support user lists. See [https://jikan.docs.apiary.io/#reference/0/user](https://jikan.docs.apiary.io/#reference/0/user).

I'm deprecating Kuristina, please use Jikan from now on.
